### PR TITLE
NGI0 - Updating licensing aspects according REUSE

### PR DESCRIPTION
**Pull request by lnceballosz**
Hello,
I would like to propose some updates regarding copyright and licensing information. [REUSE](https://reuse.software/) specifications intend to make licensing easier by setting one way to display all this legal information through comment headers on source files that can be human - and machine – readable. 
Feel completely free to adopt these specifications by merging this pull request.

### REUSE Features:

- SPDX copyright and license comment headers for all relevant files 

- LICENSES directory with all licenses used on the repository

- Licensing of image files (please be aware that I licensed the image file under the MIT license, but you can also use another license, in this case please do not forget to add the selected license text to the LICENSES folder that I have created within the repository)

### Files missing copyright and licensing information:

I added the comment headers with copyright and license information to some of the files that lacked that information. Please take into consideration that some files such as ".list" were not modified. However, we suggest to license these files under the CC0-1.0 license. (in this case please do not forget to add the selected license text to the LICENSES folder that I have created)

I provided license information to README file as well.

Please also double check if the personal information in the headers is correct and consistent

### No contribution policy:

We have noticed that your project does not have a contribution policy. Therefore, we strongly recommend you to implement one. To get further information about this please check our documentation: https://download.fsfe.org/NGI0/V2/FSFE%20-%204%20-%20Free%20Software%20Contribution%20Policy.pdf

### Further REUSE compliance

In case you find REUSE useful, we offer [a wide range of tools](https://reuse.software/dev/) to help you to continuously check and display compliance with the REUSE guidelines.

Hope that helps and thank you very much for the amazing job!

### CODE REVIEW

**Comment by Potherca** [comment]
Hi! Thank you for bringing this to our attention!

I'm am not sure if we'll be using your MR as-is but I definitely intend to follow-up based on your work.
Thinking out loud, three things come to mind:

1. I'd like to familiarize myself with the https://reuse.software/spec/
2. We might want implement this in other PDS Interop repos
3. When added, I think I'd also like to add [the `reuse` lint](https://reuse.software/dev/) to our CI/CD pipeline to ensure all future additions and changes also adhere to the conventions as defined in the REUSE spec.

Our next all-hands meeting is this Friday, I'll make sure to bring this up and report any decision back here afterwords.

Again, thank you for this!

**Comment by lucaslasota** [comment]
Hi Potherca,

these are great news! Thanks a lot for taking REUSE into consideration. This PR served also only as an example of how to implement the specifications.

In case you need more information during the implementation phase, please feel free to follow up!

Thanks for the great work!

**Comment by Potherca** [comment]
We've discussed updating licensing aspects according REUSE, everyone agrees. :tada: 

The only change that needs to happen is attributing ownership to the (contributors to) PDS Interop rather than `michiel@unhosted.org`, add the how/why to our contributing documents, and adding a github action for linting future file additions.

I'll take care of these when time allows :+1:

**Comment by lucaslasota** [comment]
Wow, excellent news! Please feel free to follow up with any questions! 
Thanks a lot!

**Comment by Potherca** [comment]
Just a small reminder that this _is_ on our roadmap and has not been forgotten, despite inaction on this ticket.

**Comment by Potherca** [comment]
Closing in favor of #58

**Pull request closed without merging**
